### ISSUE TITLE
do not accept answer with bad kanas

### ISSUE THREAD

**Issue by gaul** [baileysnyder/japanese-conjugation#1]
Instead of flagging answers with bad kanas as incorrect, could the app show an error dialog or similar?  These happen when making typos and something that Wanikani does as well.  An example:

![image](https://user-images.githubusercontent.com/848247/76698007-2bfe9200-66e1-11ea-95c2-a1706d55e141.png)

**Comment by baileysnyder** [comment]
Yep makes sense - fixed. I added a tooltip that pops up when you submit non-Japanese characters.
![image](https://user-images.githubusercontent.com/43757445/115979107-8fe0c480-a549-11eb-8cb8-8e2e096b79e9.png)
