### ISSUE TITLE
Hide meaning

### ISSUE THREAD

**Issue by Shagon94** [baileysnyder/japanese-conjugation#14]
Allow for an option to hide the definition of the word, so instead of `難しい` and then the word `difficult` below it just show the kanji

**Comment by baileysnyder** [comment]
I think this is a good idea. Someone focused purely on conjugation might see the English translation as unnecessary noise. I'll take a look at it tomorrow 👍

**Comment by baileysnyder** [comment]
Should be live on the site now. Thanks for the suggestion @Shagon94 :)
