### ISSUE TITLE
Furigana and kanji equivalence

### ISSUE THREAD

**Issue by dominicchase** [baileysnyder/japanese-conjugation#23]
Sometimes answers using kanji are considered incorrect even if they are equivalent to the furigana answer. An example of this is 合わなかった is incorrect for 会う in the negative past improper.

**Comment by baileysnyder** [comment]
It looks like your IME is giving you **合**わなかった instead of **会**わなかった. I tested to make sure and 会わなかった was accepted - hopefully that was the issue.
