### ISSUE TITLE
Should accept -じゃありません and -ではありません forms

### ISSUE THREAD

**Issue by 13597** [baileysnyder/japanese-conjugation#39]
Example:

色々
Present tense Negative Polite

What is currently accepted:

色々じゃないです
色々ではないです

What should be added:

色々じゃありません 
色々ではありません

**Comment by baileysnyder** [comment]
They appear to be working for me:
![image](https://github.com/user-attachments/assets/ce4b435c-97b5-4d42-8d60-ecf66e4de4e7)
![image](https://github.com/user-attachments/assets/764475c3-3f55-443c-a9a1-eed68b9b8280)

Can you recreate the issue @13597 and send screenshots?

**Comment by 13597** [comment]
You are right, I'm sorry.
