### ISSUE TITLE
Support for other verb valid conjugations

### ISSUE THREAD

**Issue by Kaerum** [baileysnyder/japanese-conjugation#6]
Now I have only recently studied this so I might be wrong but this app does not accept ないです and なかったです endings for negative past polite conjugations of うーVerbs.

**Comment by baileysnyder** [comment]
I completely missed that, thanks for pointing it out :] I added them in my most recent code push: https://github.com/baileysnyder/japanese-conjugation/commit/f71b336c9f6f658722c10702f374bedf4acbddc1
