### ISSUE TITLE
Support alternative kanji/kana spellings when accepting kanji input

### ISSUE THREAD

**Issue by Type-kun** [baileysnyder/japanese-conjugation#8]
![image](https://user-images.githubusercontent.com/3628092/139405503-a8e05929-0e88-4492-800b-369581498bcb.png)

For example, when trying to input つまらない through IME, the first suggested variant seems to be 詰まらない rather than 詰らない. It would be nice if both could be accepted as correct.

**Comment by baileysnyder** [comment]
@Type-kun Good catch! I fixed it in my recent push https://github.com/baileysnyder/japanese-conjugation/commit/ae5f61a255b8f9003fddfb31308d599d01f12795

Almost all of the words have some outdated rarely used spelling so I didn't include all of them, but I added these ones that stuck out:

**詰らない**
詰まらない

**上がる**
上る

**真っ直ぐ**
真っすぐ
真直ぐ
真すぐ

Thanks for pointing it out :] Let me know if there were any other major ones you could find
